apiVersion: v1
kind: pod
metadata:
  name: alpine-pod
spec:
  containers:
    - image: alpine
      command:
        - sleep
      args:
        - 1d
      env:
        - name: test
        - name: hello