apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    app: myrc
  template:
    metadata:
      name: myrc
      labels:
        app: myrc
    spec:
      containers:
        - name: myapp
          image: nginx:1.16
          ports:
            - containerPort: 80
