apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    name: pod
spec:
  restartPolicy: Never
  containers:
  - name: pod
    image: nginx:1.16
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    name: pod
spec:
  restartPolicy: onfailure
  containers:
  - name: pod
    image: nginx:1.16
    ports:
      - containerPort: 80