apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - image:  nginx:1.16
      name:  jenkins-container
      ports:
        - containerPort: 80
          protocol: TCP
  containers:
    - image:  jenkins/jenkins: lts-jdk11
      name: jenkins-container
      ports:
      - name:  Port Name
        ports:
          - containerPort: 8080
             protocol: TCp